[package]
name = "tlang"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
lazy_static = "1.5.0"
libc = "0.2.174"
libffi = { version = "4.1.1" }

[dev-dependencies]
pretty_assertions = "1.4.1"
